// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1AyBcxW88V9tz1d1Sf6ht_QqD0LOFow',
    appId: '1:992073294013:web:136d1f7c5346868cad17d4',
    messagingSenderId: '992073294013',
    projectId: 'fir-test-be88e',
    authDomain: 'fir-test-be88e.firebaseapp.com',
    storageBucket: 'fir-test-be88e.firebasestorage.app',
    measurementId: 'G-LQESHD0NBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jxYlCCPM2OYpwgNEJQ21mrSZHCzrONU',
    appId: '1:992073294013:android:6f86a8d2dc630805ad17d4',
    messagingSenderId: '992073294013',
    projectId: 'fir-test-be88e',
    storageBucket: 'fir-test-be88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBigrytfPYLVw9A67ohknREDepT2J7IA3M',
    appId: '1:992073294013:ios:82538b216b584d9aad17d4',
    messagingSenderId: '992073294013',
    projectId: 'fir-test-be88e',
    storageBucket: 'fir-test-be88e.firebasestorage.app',
    iosBundleId: 'com.example.authenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBigrytfPYLVw9A67ohknREDepT2J7IA3M',
    appId: '1:992073294013:ios:82538b216b584d9aad17d4',
    messagingSenderId: '992073294013',
    projectId: 'fir-test-be88e',
    storageBucket: 'fir-test-be88e.firebasestorage.app',
    iosBundleId: 'com.example.authenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd1AyBcxW88V9tz1d1Sf6ht_QqD0LOFow',
    appId: '1:992073294013:web:973fad13308b626ead17d4',
    messagingSenderId: '992073294013',
    projectId: 'fir-test-be88e',
    authDomain: 'fir-test-be88e.firebaseapp.com',
    storageBucket: 'fir-test-be88e.firebasestorage.app',
    measurementId: 'G-1GSD3RVP29',
  );
}
